CREATE TABLE IF NOT EXISTS gateway_approvals (
  id                 VARCHAR(128) NOT NULL PRIMARY KEY,
  account_id         VARCHAR(64)  NOT NULL,
  workspace_id       VARCHAR(64)  NULL,
  gateway_id         VARCHAR(128) NOT NULL,
  session_id         VARCHAR(128) NOT NULL,
  user_id            VARCHAR(64)  NOT NULL,
  request_id         VARCHAR(128) NOT NULL,
  source             VARCHAR(32)  NOT NULL,
  status             VARCHAR(32)  NOT NULL DEFAULT 'pending',
  risk               VARCHAR(32)  NOT NULL DEFAULT 'medium',
  title              VARCHAR(255) NOT NULL,
  summary            TEXT         NOT NULL,
  reason             TEXT         NULL,
  tool_name          VARCHAR(128) NULL,
  input_preview_json MEDIUMTEXT   NULL,
  input_hash         VARCHAR(128) NULL,
  event_id           BIGINT       NULL,
  event_seq          BIGINT       NULL,
  turn_id            VARCHAR(128) NULL,
  decided_by         VARCHAR(64)  NULL,
  decided_at         TIMESTAMP    NULL,
  expires_at         TIMESTAMP    NULL,
  created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_gateway_approvals_session_request (session_id, request_id),
  KEY idx_gateway_approvals_user_status (account_id, user_id, status, created_at),
  KEY idx_gateway_approvals_session (account_id, gateway_id, session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gateway_approval_audit (
  id          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  approval_id VARCHAR(128) NOT NULL,
  account_id  VARCHAR(64)  NOT NULL,
  gateway_id  VARCHAR(128) NOT NULL,
  session_id  VARCHAR(128) NOT NULL,
  actor_id    VARCHAR(64)  NULL,
  action      VARCHAR(32)  NOT NULL,
  metadata_json MEDIUMTEXT NULL,
  created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_gateway_approval_audit_action_actor (approval_id, action, actor_id),
  KEY idx_gateway_approval_audit_approval (approval_id, created_at),
  KEY idx_gateway_approval_audit_scope (account_id, gateway_id, session_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
