export type WebLocale = 'zh' | 'en';

export const WEB_LOCALE_STORAGE_KEY = 'tether:webLocale';
export const WEB_THEME_STORAGE_KEY = 'tether:webTheme';

export const WEB_COPY = {
  zh: {
    appName: 'Tether',
    sessionShell: '会话控制台',
    sessionShellDescription: '连接已有终端会话，按连接模式切换直连或 Relay。',
    managementShellTitle: '管理域占位',
    managementShellDescription: '当前先验证管理域登录壳子与 realm 隔离，完整后台属于后续阶段。',
    managementShellNote: '当前只验证 auth route shell、realm 隔离和后续 `/admin` 入口占位，不把管理 token 接到 terminal control。',
    signOut: '退出登录',
    backToSessions: '返回会话控制台',
    connection: '连接',
    direct: '直连',
    relay: 'Relay',
    relayUrl: 'Relay 地址',
    relaySecret: '密钥',
    relaySecretPlaceholder: 'Relay 密钥',
    transport: '传输',
    mode: '模式',
    control: '控制',
    observe: '观察',
    httpFallback: 'HTTP 兜底',
    stop: '停止',
    stopAll: '全部停止',
    noSessions: '暂无 session',
    noSessionsDescription: '先用 CLI 启动一个 session，然后刷新本页。',
    activeSessions: '活跃',
    history: '历史',
    gatewayList: 'Gateway 列表',
    sendToAgent: '发送给 Agent',
    send: '发送',
    statusLoading: '加载中',
    statusConnecting: '连接中',
    statusDisconnected: '已断开',
    statusExited: '已退出',
    statusStopping: '正在停止',
    statusStopRequested: '已发送停止请求',
    statusSending: '正在发送',
    statusSyncingWs: '正在同步 · WS',
    statusSyncingHttp: '正在同步 · HTTP 兜底',
    statusReplaying: '正在回放',
    statusRelayAuth: '正在验证 Relay',
    statusRelayInvalid: 'Relay 地址无效',
    statusRelayBadFrame: 'Relay 数据格式错误',
    statusRelayClosed: 'Relay 已断开',
    statusRelayError: 'Relay 连接错误',
    statusRelayUnavailable: 'Relay 未连接',
    statusStreamBadFrame: '数据流格式错误',
    statusStreamError: '数据流错误',
    statusStreamUnavailable: '数据流不可用',
    statusInputFailed: '输入失败',
    statusObserveCannotInput: '观察模式不能输入',
    statusRelaySent: '已发送 · Relay',
    statusHttpSent: '已发送 · HTTP',
    statusWsSent: '已发送 · WS',
    controller: '控制端',
    clients: '个客户端',
    authFailed: '认证失败',
    gatewayNotConnected: 'Gateway 未连接',
    sessionNotSubscribed: '客户端尚未订阅该 session',
    observeCannotSend: '观察模式不能输入',
    observeCannotResize: '观察模式不能调整终端尺寸',
    fillRelayUrl: '请填写 Relay 地址',
    relayProtocolInvalid: 'Relay 地址必须使用 ws、wss、http 或 https',
    sessionRunning: '运行中',
    sessionStopped: '已停止',
    sessionCompleted: '已完成',
    sessionFailed: '失败',
    sessionLost: '失联',
    localeLabel: '语言',
    themeLabel: '主题',
    chinese: '中文',
    english: 'English',
    light: '浅色',
    dark: '深色',
    normalSignInTitle: '普通用户登录',
    normalSignInDescription: '登录后进入 Tether 会话控制台，继续使用已存在的终端 session。',
    normalRegisterTitle: '创建普通账户',
    normalRegisterDescription: '用 `/register` 创建这个 Tether workspace 的首个 owner 账户。',
    managementSignInTitle: '管理域登录',
    managementSignInDescription: '管理域和普通用户会话隔离，不直接接管 terminal control。',
    managementRegisterTitle: '开通管理域',
    managementRegisterDescription: '管理域使用独立浏览器登录态，和普通用户会话分开存储。',
    emailLabel: '账户名',
    passwordLabel: '密码',
    displayNameLabel: '显示名称',
    emailPlaceholder: 'name@example.com',
    adminEmailPlaceholder: 'admin@example.com',
    passwordPlaceholder: '至少 8 位密码',
    displayNamePlaceholder: 'Dream',
    operatorPlaceholder: 'Operator',
    signIn: '登录',
    signingIn: '登录中…',
    createAccount: '创建账户',
    creatingAccount: '创建中…',
    managementEntry: '进入管理域',
    settingUpManagement: '开通中…',
    setupManagement: '开通管理域',
    noAccountYet: '还没有账户？去注册',
    alreadyHaveAccount: '已有账户？去登录',
    noAdminYet: '还没有管理账户？去注册',
    adminReady: '已经开通过？去登录',
    authSurface: '会话访问域',
    managementSurface: '管理访问域'
  },
  en: {
    appName: 'Tether',
    sessionShell: 'Session Shell',
    sessionShellDescription: 'Attach to existing terminal sessions and switch between direct mode and Relay.',
    managementShellTitle: 'Management Shell Placeholder',
    managementShellDescription: 'This route currently validates the management realm shell and isolation. The full admin console belongs to a later phase.',
    managementShellNote: 'This page only validates the auth shell, realm isolation, and the future `/admin` entry. Management tokens are not wired into terminal control here.',
    signOut: 'Sign out',
    backToSessions: 'Back to session shell',
    connection: 'Connection',
    direct: 'Direct',
    relay: 'Relay',
    relayUrl: 'Relay URL',
    relaySecret: 'Secret',
    relaySecretPlaceholder: 'Relay secret',
    transport: 'Transport',
    mode: 'Mode',
    control: 'Control',
    observe: 'Observe',
    httpFallback: 'HTTP fallback',
    stop: 'Stop',
    stopAll: 'Stop all',
    noSessions: 'No active sessions',
    noSessionsDescription: 'Start a session from the CLI, then refresh this page.',
    activeSessions: 'Active',
    history: 'History',
    gatewayList: 'Gateway List',
    sendToAgent: 'Send to agent',
    send: 'Send',
    statusLoading: 'Loading',
    statusConnecting: 'Connecting',
    statusDisconnected: 'Disconnected',
    statusExited: 'Exited',
    statusStopping: 'Stopping',
    statusStopRequested: 'Stop request sent',
    statusSending: 'Sending',
    statusSyncingWs: 'Syncing · WS',
    statusSyncingHttp: 'Syncing · HTTP fallback',
    statusReplaying: 'Replaying',
    statusRelayAuth: 'Verifying Relay',
    statusRelayInvalid: 'Invalid Relay URL',
    statusRelayBadFrame: 'Invalid Relay payload',
    statusRelayClosed: 'Relay disconnected',
    statusRelayError: 'Relay connection error',
    statusRelayUnavailable: 'Relay unavailable',
    statusStreamBadFrame: 'Invalid stream payload',
    statusStreamError: 'Stream error',
    statusStreamUnavailable: 'Stream unavailable',
    statusInputFailed: 'Input failed',
    statusObserveCannotInput: 'Observe mode cannot send input',
    statusRelaySent: 'Sent · Relay',
    statusHttpSent: 'Sent · HTTP',
    statusWsSent: 'Sent · WS',
    controller: 'Controller',
    clients: 'clients',
    authFailed: 'Authentication failed',
    gatewayNotConnected: 'Gateway is not connected',
    sessionNotSubscribed: 'Client is not subscribed to this session',
    observeCannotSend: 'Observe mode cannot send input',
    observeCannotResize: 'Observe mode cannot resize',
    fillRelayUrl: 'Please enter a Relay URL',
    relayProtocolInvalid: 'Relay URLs must use ws, wss, http, or https',
    sessionRunning: 'Running',
    sessionStopped: 'Stopped',
    sessionCompleted: 'Completed',
    sessionFailed: 'Failed',
    sessionLost: 'Lost',
    localeLabel: 'Language',
    themeLabel: 'Theme',
    chinese: '中文',
    english: 'English',
    light: 'Light',
    dark: 'Dark',
    normalSignInTitle: 'Sign in',
    normalSignInDescription: 'Sign in to the Tether session shell and continue working with existing terminal sessions.',
    normalRegisterTitle: 'Create your account',
    normalRegisterDescription: 'Use `/register` to create the first owner account for this Tether workspace.',
    managementSignInTitle: 'Management sign in',
    managementSignInDescription: 'Management access stays isolated from the normal user session surface and never unlocks terminal control.',
    managementRegisterTitle: 'Set up management access',
    managementRegisterDescription: 'Management access uses its own browser auth record and stays separate from normal user sessions.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    displayNameLabel: 'Display name',
    emailPlaceholder: 'name@example.com',
    adminEmailPlaceholder: 'admin@example.com',
    passwordPlaceholder: 'Minimum 8 characters',
    displayNamePlaceholder: 'Dream',
    operatorPlaceholder: 'Operator',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    createAccount: 'Create account',
    creatingAccount: 'Creating account…',
    managementEntry: 'Enter management',
    settingUpManagement: 'Setting up…',
    setupManagement: 'Set up management',
    noAccountYet: "Don't have an account? Register",
    alreadyHaveAccount: 'Already have an account? Sign in',
    noAdminYet: 'Need an admin account? Register',
    adminReady: 'Already set up? Sign in',
    authSurface: 'Session access realm',
    managementSurface: 'Management access realm'
  }
} as const;

export function getWebCopy(locale: WebLocale) {
  return WEB_COPY[locale];
}
